directory: ~/mp3zrenamed
library: ~/data/musiclibrary.db
orignial_date: yes
import:
    copy: no
    write: no
    duplicate_action: keep
    quiet_fallback: asis
plugins: chroma lastgenre bpmanalyser fetchart ftintitle fromfilename rewrite
lastgenre:
    source: track
match: 
   strong_rec_thresh: 0.3
   max_rec:
       missing_tracks: strong
asciify_paths: yes
fetchart:
   enforce_ratio: yes
   store_source: yes
   cover_names: cover.jpg
ftintitle:
   format: (ft. {0})
format_item: $albumartist - $album/$track $title :$genre
max_filename_length: 39
max_filename_length: 42
paths:
   default: $albumartist - $album%aunique{}/$track $title
replace:
    '[\\/]':
    '^\.':
    '[\x00-\x1f]':
    '[<>:"\?\*\|]':
    '\.$':
    '\s+$': ''
    '^\s+': ''
    '^-':
rewrite:
   artist At the Drive‐In: At the Drive In
   artist AC/DC: ACDC
   artist ?Weird Al? Yankovic: Weird Al Yankovic
