directory: ~/mp3zrenamed
library: ~/data/musiclibrary.db
orignial_date: yes
import:
    copy: no
    write: no
    duplicate_action: keep
    quiet_fallback: asis
plugins: chroma lastgenre bpmanalyser fetchart ftintitle fromfilename rewrite embedart convert replaygain zero acousticbrainz ihate
ihate:
   skip:
        - artist:Weezer
acousticbrainz:
   force: no
replaygain:
    backend: ffmpeg
zero:
    fields: albumartist_sort artist_sort composer_sort albumartist_sort
lastgenre:
    source: track
match: 
   strong_rec_thresh: 0.3
   max_rec:
       missing_tracks: strong
asciify_paths: yes
convert:
   auto: yes
   copy_album_art: yes
   never_convert_lossy_files: yes
   quiet: no   
fetchart:
   enforce_ratio: yes
   store_source: yes
   cover_names: cover.jpg
embedart:
   ifempty: yes
ftintitle:
   format: (ft. {0})
format_item: $albumartist - $album/$track $title :$genre :$art_source :$bpm
max_filename_length: 39
max_filename_length: 42
paths:
   default: $albumartist - $album%aunique{}/$track $title
   comp: Various Artists - $album%aunique{}/$track $title
replace:
    '[\\/]':
    '^\.':
    '[\x00-\x1f]':
    '[<>:"\?\*\|]':
    '\.$':
    '\s+$': ''
    '^\s+': ''
    '^-':
    '  ': ' '
    '\./':
    'Greatest Hits So Far\.': 'Greatest Hits So Far'
#This is to replace forward slash / in filename with space instead of underscore
path_sep_replace: ''
rewrite:
   artist At the Drive‐In: At the Drive In
   artist .*Weird Al.*Yankovic: Weird Al Yankovic
   artist AC/DC: ACDC
