directory: ~/music
library: ~/data/musiclibrary.db
orignial_date: yes
import:
    copy: no
    write: no
    duplicate_action: keep
plugins: chroma lastgenre
lastgenre:
    source: track
match: 
   strong_rec_thresh: 0.3
   max_rec:
       missing_tracks: strong
