#!/bin/bash
OSTYPE="linux"
VERSION="6"
VCPUS="2"
RAM="1024"
INTERFACES=( 199 141 69 )
FILESIZE="8"
SYSTYPE="dns6"
COMMON="$OSTYPE$VERSION"
#EXTRAKEYS="1-faucet5"
HOSTNAMEOVERRIDE="faucet5.userworld.com"
DISKS=( "path=/virt/images/$HOSTNAME.img,device=disk,bus=virtio,format=raw,size=$FILESIZE" "path=/virt/images/${HOSTNAME}-data.img,device=disk,bus=virtio,size=1" )
. /virt/vm_configs/$COMMON
