#!/bin/bash
OSTYPE="linux"
VERSION="8"
VCPUS="2"
RAM="4192"
#54:52:0a:00:8d:6a
INTERFACES=( 199 141 )
FILESIZE="10"
SYSTYPE="r8"
COMMON="$OSTYPE$VERSION"
EXTRAKEYS=""
#HOSTNAMEOVERRIDE="cold1.userworld.com"
#. /virt/vm_configs/$COMMON
OSVARIANT="rhel6"
KSFILE="r8kvm.test.ks"
#LOCATION="http://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/"
#LOCATION="http://10.0.141.13/centos/8/BaseOS/x86_64/os/"
LOCATION="http://10.0.141.13/rocky/8/BaseOS/x86_64/os/"
