#!/bin/bash
OSTYPE="linux"
VERSION="6"
VCPUS="2"
RAM="2048"
INTERFACES=( 199 131 69 )
FILESIZE="10"
SYSTYPE="sink"
COMMON="$OSTYPE$VERSION"
#EXTRAKEYS="1-sink"
HOSTNAMEOVERRIDE="tap-test2.oreillyschool.com"
. /virt/vm_configs/$COMMON
