#!/bin/bash
OSTYPE="linux"
VERSION="6"
VCPUS="1"
RAM="512"
INTERFACES=( 199 141 25 )
FILESIZE="8"
SYSTYPE="vpn"
#Uncomment the follow to add extra spacewalk keys
EXTRAKEYS="1-vpn1"
COMMON="$OSTYPE$VERSION"
HOSTNAMEOVERRIDE="uwvpn1.userworld.com"
. /virt/vm_configs/$COMMON
