# Kickstart file automatically generated by anaconda.

#version=RHEL6
#virt-install --hvm --accelerate --vnc --noautoconsole --os-type=linux --os-variant=rhel6 --file=/virt/images/svn-fastdir.img --file-size=8 --name svn-fastdir --vcpus 2 --ram 1024 --network=bridge:br199 --network=bridge:br131 --location http://ks.local.useractive.com/centos/6/os/x86_64/ --initrd-inject=/virt/vm_configs/userworld/svn-fastdir.ks --extra-args "ks=file:/svn-fastdir.ks console=tty0 console=ttyS0"; virsh console svn-fastdir
#VISUAL="sed -i -e s/'utc'/'localtime'/" virsh edit svn-fastdir
install
url --url=http://ks.local.useractive.com/centos/6/os/x86_64
lang en_US.UTF-8
cmdline
keyboard us
network --device eth0 --bootproto static --ip=199.27.148.80 --netmask=255.255.248.0 --gateway=199.27.144.1 --nameserver=199.27.148.66 --nameserver=199.27.148.67 --noipv6 --activate
network --device eth1 --bootproto static --ip=10.0.131.80 --netmask=255.255.255.0 --noipv6 --activate
rootpw  --iscrypted $6$bkMno8HZ7ySqgI9d$yXowt4euk28.8UFMX6nd.8ztk02qdTsqUX.8MfAanxac3O3ydOcYS0h0rRaSFcDWZSOgMtxmXuZYIDNdmhfZE/
# Reboot after installation
reboot
firewall --disabled
authconfig --enableshadow --passalgo=sha512 --enablefingerprint
selinux --disabled
timezone America/Chicago
bootloader --location=mbr --driveorder=vda --append="console=ttyS0n8 crashkernel=auto"
# The following is the partition information you requested
# Note that any partitions you deleted are not expressed
# here so unless you clear all partitions first, this is
# not guaranteed to work
zerombr
clearpart --all --drives=vda --initlabel


part /boot --fstype=ext4 --size=500
part swap --asprimary --size=960
part / --fstype=ext4 --grow --asprimary --size=200
repo --name="CentOS"  --baseurl=http://ks.local.useractive.com/centos/6/os/x86_64/ --cost=100
#repo --name="cr"  --baseurl=http://ks.local.useractive.com/centos/6/cr/x86_64/ --cost=100
repo --name="ostyum"  --baseurl=http://ks.local.useractive.com/ostyum/centos/6/x86_64/ --cost=100
repo --name="rhtools"  --baseurl=http://ks.local.useractive.com/rhtools/el/6/x86_64/ --cost=100

%pre
echo "search local.useractive.com" >>/etc/resolv.conf
%end

%packages --nobase
@Core
acpid
bind-utils
bridge-utils
emacs-nox
epel-release
man
nano
nfs-utils
nfs4-acl-tools
ntp
openssh-clients
osad
ostyum-release
rhn-setup
rhncfg-actions
rpmforge-release
rsync
sssd
sssd-client
tcpdump
traceroute
vim-enhanced
wget
-acl
-aic94xx-firmware
-atmel-firmware
-attr
-audit
-authconfig
-b43-openfwwf
-basesystem
-bfa-firmware
-efibootmgr
-filesystem
-iptables-ipv6
-ipw2100-firmware
-ipw2200-firmware
-ivtv-firmware
-iwl1000-firmware
-iwl3945-firmware
-iwl4965-firmware
-iwl5000-firmware
-iwl5150-firmware
-iwl6000-firmware
-iwl6050-firmware
-libertas-usb8388-firmware
-newt-python
-policycoreutils
-ql2100-firmware
-ql2200-firmware
-ql23xx-firmware
-ql2400-firmware
-ql2500-firmware
-rt61pci-firmware
-rt73usb-firmware
-setup
-system-config-firewall-base
-xorg-x11-drv-ati-firmware
-zd1211-firmware

%end

%post

%end
