[global]
keyboard = "en-us"
country = "us"
fqdn = "pve2.trentjohnson.net"
mailto = "me@me.com"
timezone = "America/Chicago"
root-password = "Goatman1"
root-ssh-keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDMEFJLHUXdVfnJ71zabt7P2YSHVe8fE/ueFUH9Rc2uUsJqiBK9l8g/0yfzqoFexdVjgOH3/B4/xvpShJTar0+/FaGOSWPq6KA36KxfBFurLPeA7ngD0j2D/yCx8dXJIziyveFf9bNJYYT0vQBU0pIlsGjfaRhFye2CKzCA0T2jQQ== tljohnsn@smack.office.useractive.com",
    "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAlRchb+Hm1VM7dYqDZ0D6zCtnf/dH5ba4NkGZ9gFGkHdgQLlepCCYuOUnoCr0N40lQWGdOuCVsWVEsClzRNmLTBXNgF4uDVx+S1Zw/uw/zJ89jWT/WdPr6+hT2s7z8OBe1HGI3zyW7ftzBpUWE9W2qiiPXwUXUAOvn+pX15DPrjE= newlaptopkey"
]

[network]
source = "from-dhcp"

[network.interface-name-pinning]
enabled = false

#[network.interface-name-pinning.mapping]
#"24:8a:07:1e:05:bc" = "lan0"
#"24:8a:07:1e:05:bd" = "lan1"
#"b4:2e:99:ac:ad:b4" = "mgmt"

[disk-setup]
filesystem = "ext4"
#zfs.raid = "raid0"
disk-list = ["nvme0n1"]
lvm.minfree = 500
#disk-list = ["nvme0n1","sda"]

#[post-installation-webhook]
#url = "https://my.endpoint.local/postinst"
#cert-fingerprint = "AA:E8:CB:95:B1:..."

[first-boot]
source = "from-iso"
ordering = "network-online"
#ordering = "before-network"
